let d = new Date()
console.log(d)
console.log(`LocalTimeString ${d.toLocaleTimeString()}`)
console.log(`Now ${Date.now()}`)
console.log(`Time ${d.getTime()}`)
console.log(`Hours ${d.getHours()}`)
console.log(`Minutes ${d.getMinutes()}`)
console.log(`Seconds ${d.getSeconds()}`)
console.log(`Miliseconds ${d.getMilliseconds()}`)